# Generated by Django 5.1.1 on 2024-10-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
